trustPolicy: no-downgrade
minimumReleaseAge: 0

packages:
  - packages/*

shamefullyHoist: true
strictPeerDependencies: false
shellEmulator: true
ignoreWorkspaceRootCheck: true
trustPolicyExclude:
  - undici-types@6.20.0
  - '@pnpm/modules-yaml'
  - tinyexec@1.2.2

refs:
  devframe: &devframe ^0.7.15
  nuxt-devtools: &nuxt-devtools ^4.0.0-alpha.9
  vite-devtools: &vite-devtools ^0.4.10

overrides:
  '@devframes/hub': *devframe
  '@nuxt/devtools': *nuxt-devtools
  '@nuxt/devtools-kit': *nuxt-devtools
  '@vitejs/devtools': *vite-devtools
  '@vitejs/devtools-kit': *vite-devtools
  '@vitejs/devtools-rolldown': *vite-devtools
  chokidar: 5.0.0
  devframe: *devframe
  semver: 7.8.0

patchedDependencies:
  '@nuxt/nitro-server-nightly@5.0.0-29666842.2bab300c': patches/@nuxt__nitro-server-nightly@5.0.0-29666842.2bab300c.patch

catalogs:
  bundling:
    '@unocss/nuxt': ^66.7.5
    '@vueuse/nuxt': ^14.4.0
    nuxt: npm:nuxt-nightly@5x
    rollup: ^4.62.3
    unbuild: ^3.6.1
    vite: ^8.2.0
  deps:
    '@modelcontextprotocol/sdk': ^1.30.0
    ansis: ^4.3.1
    cac: ^7.0.0
    devframe: *devframe
    get-port-please: ^3.2.0
    h3: ^2.0.1-rc.26
    ohash: ^2.0.11
    p-limit: ^7.3.1
    pathe: ^2.0.3
    tinyexec: ^1.2.4
    tinyglobby: ^0.2.17
    unconfig: ^7.5.0
    valibot: ^1.4.2
    verkit: ^0.3.1
  dev:
    '@antfu/ni': ^30.3.0
    '@nuxt/devtools': *nuxt-devtools
    bumpp: ^12.1.1
    skills-npm: ^1.2.0
    typescript: ^6.0.3
    vite-plugin-inspect: ^12.0.2
    vue-tsc: ^3.3.8
  frontend:
    d3: ^7.9.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    floating-vue: ^5.2.2
    fuse.js: ^7.5.0
    modern-screenshot: ^4.7.0
    nanovis: ^1.0.0
    theme-vitesse: ^1.0.0
    vue-i18n: ^11.2.8
  icons:
    '@iconify-json/carbon': ^1.2.24
    '@iconify-json/catppuccin': ^1.2.17
    '@iconify-json/logos': ^1.2.11
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/ri': ^1.2.10
    '@iconify-json/simple-icons': ^1.2.92
  inlined:
    '@antfu/utils': ^9.3.0
  lint:
    '@antfu/eslint-config': ^9.2.0
    '@nuxt/eslint': ^1.16.0
    '@typescript-eslint/utils': ^8.65.0
    '@unocss/eslint-config': ^66.7.5
    eslint: ^10.8.0
    nano-staged: ^1.0.2
    nuxt-eslint-auto-explicit-import: ^0.2.0
    simple-git-hooks: ^2.13.1
  testing:
    '@axe-core/playwright': ^4.12.1
    '@playwright/test': ^1.62.1
    vitest: ^4.1.10
  types:
    '@types/d3': ^7.4.3
    '@types/d3-hierarchy': ^3.1.7
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true
